version: 2
jobs:
  build-deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - add_ssh_keys
#          fingerprints:
#            - "${SSH_FINGERPRINT}"
      #- run: ssh-keyscan -H ${SSH_SERVER} >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            echo '${SSH_KNOWN_HOST}' >> ~/.ssh/known_hosts
            scp -o StrictHostKeyChecking=no -P ${SSH_PORT} -r ~/repo/build/libs/*.war ${SSH_USER}@${SSH_HOST}:~/circleciuploads/tomcat.staging/map.war

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy
